/*
 * This file is part of DisplayRT.
 *
 * Copyright (C) 2024-2025 Keran Ye <keran.ye@email.ucr.edu>
 *
 * DisplayRT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DisplayRT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DisplayRT. If not, see <https://www.gnu.org/licenses/>.
 *
 * Author(s): 
 * - Keran Ye (keran.ye@email.ucr.edu)
 * 
 * The content of this file is about testing multiple-window display using DisplayRT. 
 * The display property is generated by the custom yaml parer. 
 * The real time data is broadcast with custom messages through ROS2.
 */

#include <memory>
#include <iostream>
#include <filesystem>
#include <thread>
#include <chrono>
#include <cstdlib>
#include <string>

#include <QtWidgets/QApplication>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QGridLayout>
#include <QtCore/QTimer>

// displayrt
#include "displayRT.h"
#include "displayRT_parser.h"

#include "myDisplayWithROS2.h"

// ROS2
#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"
#include "displayrt_example_ros2/msg/imu.hpp"
#include "displayrt_example_ros2/msg/sensors.hpp"
#include "displayrt_example_ros2/msg/revolute_servo.hpp"
#include "displayrt_example_ros2/msg/servos.hpp"


using namespace display_rt; // for DisplayRT
using namespace std::chrono_literals;
using std::placeholders::_1;

int main(int argc, char *argv[])
{
    std::string new_config_path;

    { // get config file path
      // current working directory
      std::filesystem::path cwd = std::filesystem::current_path();

      // std::string new_config_path;
      if (argc > 1)
      {
        // loop through command line arguments
        for (int i = 1; i < argc; i++)
        {
          // check if the argument is path-to-build
          if (std::string(argv[i]) == "-path-to-config")
          {
            // check if the next argument is the path
            if (i + 1 < argc)
            {
              // set the new_library_path to the next argument
              new_config_path = std::string(argv[i + 1]);
              continue;
            }
          }
        }

        // check if the new_config_path is set
        if (new_config_path.empty())
        {
          throw std::runtime_error("Please provide the relative path to the config file using the command line argument '-path-to-config <path>'");
        }
      }
      else
      {
        throw std::runtime_error("Please provide the relative path to the build directory using the command line arguments '-path-to-config <path>'");
      }

      // combine the new_config_path with the current working directory
      new_config_path = (cwd / new_config_path).string();
    }

    rclcpp::init(argc, argv);

    // myPublisherROS2 thread
    std::thread t1(
        [&]{
            std::shared_ptr<display_rt::example::myPublisherROS2> publisher = std::make_shared<display_rt::example::myPublisherROS2>();

            // spin for ROS2 publisher
            while( rclcpp::ok() )
            {
                try
                {
                    publisher->runOnce();
                }
                catch (const std::exception &e)
                {
                    std::cerr << "Exception: " << e.what() << std::endl;
                }

                // sleep for 10 ms
                std::this_thread::sleep_for(std::chrono::milliseconds(100));
            }
        }
    );

    // // mySubscriberROS2 thread
    // std::thread t2(
    //     [&]{
    //         std::shared_ptr<display_rt::example::mySubscriberROS2> subscriber = std::make_shared<display_rt::example::mySubscriberROS2>();

    //         // spin for ROS2 subscriber
    //         while( rclcpp::ok() )
    //         {
    //             try
    //             {
    //                 subscriber->spinOnce();
    //             }
    //             catch (const std::exception &e)
    //             {
    //                 std::cerr << "Exception: " << e.what() << std::endl;
    //             }

    //             std::this_thread::sleep_for(std::chrono::milliseconds(50));
    //         }
    //     }
    // );

    // myDisplayRT thread
    // parser
    // std::string path = std::filesystem::current_path().string() + "/../example/MultiwindowPlotWithParsedDisplayRT/config.yaml";
    // std::string path = std::filesystem::current_path().string() + "/config.yaml";
    // print out the path
    std::cout << "\nconfig file path: " << new_config_path << std::endl;

    Yaml::Node parser;
    std::shared_ptr<DisplayRT_Parser> display_parser = std::make_shared<DisplayRT_Parser>();
    auto display_property = display_parser->parseConfiguration( new_config_path, parser );

    std::thread t3(
        [&]{
            // display
            auto display = std::make_shared<display_rt::example::myDisplayRT_ROS2>( display_property );
            display->Initial( argc, argv); 
            display->Setup();
            display->Start(); 
        }
    );

    t1.join();
    // t2.join();
    t3.join();

    rclcpp::shutdown();

    return 0;
}